name: PR Preview Deployment

on:
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build --destination ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          allow_empty_commit: true
          cname: '' # Omit custom domain for PR preview

