name: Update schedule, artifacts, and bibliography

on:
  schedule:
    # We'll run this weekly
    - cron:  '0 12 * * 1'
  workflow_dispatch:

jobs:
  update-schedule-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
        #  channels: conda-forge,defaults
        #  channel-priority: true
          activate-environment: ols-website
          environment-file: environment.yml

      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Update Open Seeds schedule
        shell: bash -el {0}
        run: |
          bash bin/openseeds/update_schedule.sh

      - name: Update Open Seeds library
        shell: bash -el {0}
        run: |
          python bin/prepare_website_data.py buildlibrary -p "openseeds"

      - name: Update Nebula schedule
        shell: bash -el {0}
        run: |
          bash bin/nebula/update_schedule.sh

      - name: Update people data artifacts
        shell: bash -el {0}
        run: |
          python bin/prepare_website_data.py extractfullpeopledata

      - name: Update Open Seeds library artifacts
        shell: bash -el {0}
        run: |
          python bin/prepare_website_data.py extractlibrary -p "openseeds"

      - name: Update Open Seeds projects
        shell: bash -el {0}
        run: |
          python bin/prepare_website_data.py createprojecttable -p "openseeds"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update schedule and artifacts
          title: Automatic schedule & artifact update
          body: Automatic schedule update and artifacts done via GitHub Action once a week
          base: main
          branch: schedule-update
          delete-branch: true

  update-bibliography:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
        #  channels: conda-forge,defaults
        #  channel-priority: true
          activate-environment: ols-website
          environment-file: environment.yml

      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Update bibliography
        shell: bash -el {0}
        env:
          ZOTERO_API: ${{ secrets.ZoteroAPI }}
        run: |
          python bin/prepare_website_data.py updatebibliography -a "$ZOTERO_API"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update bibliography
          title: Automatic bibliography update
          body: Automatic bibliography update done via GitHub Action once a week
          base: main
          branch: bibliography-update
          delete-branch: true